package com.brewco.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class RegisterRequest {
    @NotBlank(message = "First name is required")
    private String firstName;

    @NotBlank(message = "Last name is required")
    private String lastName;

    @NotBlank(message = "Email is required")
    @Email(message = "Email should be valid")
    private String email;

    // Password is optional — auto-generated by backend and emailed
    private String password;
    private String confirmPassword;

    private String dateOfBirth;

    @NotBlank(message = "Gender is required")
    private String gender; // MALE, FEMALE, OTHER

    private String phoneNumber;

    // Role can be passed from frontend: CUSTOMER or CAFE_OWNER
    private String role;
}
